media:
  - name: media
    label: Media
    input: public
    output: /
    path: /

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: tags
        label: Tags
        type: list
        items:
          type: string

  - name: books
    label: Books
    type: collection
    path: src/content/books
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: author
        label: Author
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: rating
        label: Rating (1-5)
        type: number
        min: 1
        max: 5
        required: true
      - name: url
        label: External URL
        type: string
        required: false

  - name: games
    label: Games
    type: collection
    path: src/content/games
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: year
        label: Year
        type: number
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: rating
        label: Rating (1-5)
        type: number
        min: 1
        max: 5
        required: true
      - name: url
        label: External URL
        type: string
        required: false

  - name: movies
    label: Movies
    type: collection
    path: src/content/movies
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: year
        label: Year
        type: number
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: rating
        label: Rating (1-5)
        type: number
        min: 1
        max: 5
        required: true
      - name: url
        label: External URL
        type: string
        required: false

  - name: countries
    label: Countries
    type: collection
    path: src/content/countries
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: country
        label: Country
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: rating
        label: Rating (1-5)
        type: number
        min: 1
        max: 5
        required: true
      - name: flag
        label: Flag (image path or emoji)
        type: string
        required: true
      - name: favorite
        label: Favorite
        type: boolean
        required: false


